services:

  auth-db:
    image: postgres:15
    container_name: auth-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - beket-net

  auth_service:
    build: .
    container_name: auth_service
    ports:
      - "8080:8080"
    env_file:
      - /.env
    depends_on:
      - auth-db
    networks:
      - beket-net
  migrate:
    image: migrate/migrate
    container_name: auth-migrate
    depends_on:
      - auth-db
    networks:
      - beket-net
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@auth-db:5432/auth_db?sslmode=disable",
      "up"
    ]
networks:
  beket-net:

volumes:
  auth_data: